import { User, Task, Person, Sermon, PrayerRequest, RhythmItem } from './types';

export const USERS: User[] = [
  { id: 'u1', name: 'Pastor David Chen', role: 'owner', title: 'Lead Pastor', initials: 'DC', color: '#4f7c5f' },
  { id: 'u2', name: 'Sarah Mitchell', role: 'staff', title: 'Associate Pastor', initials: 'SM', color: '#7c6b4f' },
  { id: 'u3', name: 'Marcus Johnson', role: 'staff', title: 'Worship Director', initials: 'MJ', color: '#4f5e7c' },
  { id: 'u4', name: 'Rachel Torres', role: 'staff', title: 'Admin Assistant', initials: 'RT', color: '#7c4f6b' },
  { id: 'u5', name: 'Tyler Brooks', role: 'intern', title: 'Ministry Intern', initials: 'TB', color: '#6b7c4f' },
];

export const SAMPLE_TASKS: Task[] = [
  {
    id: 't1',
    title: 'Finalize Sunday sermon outline',
    category: 'Sermon',
    priority: 'High',
    dueDate: '2026-05-09',
    notes: 'Focus on John 15 — abiding in Christ. Needs illustration for point 2.',
    status: 'In Progress',
    visibility: 'Private',
    createdBy: 'u1',
    assignedTo: 'u1',
    createdAt: '2026-05-04T09:00:00Z',
    updatedAt: '2026-05-05T14:30:00Z',
  },
  {
    id: 't2',
    title: 'Follow up with the Henderson family',
    category: 'Care',
    priority: 'High',
    dueDate: '2026-05-07',
    notes: 'Lost their father last week. Bring meal schedule info.',
    status: 'Todo',
    visibility: 'Organization',
    createdBy: 'u1',
    assignedTo: 'u2',
    createdAt: '2026-05-05T08:00:00Z',
    updatedAt: '2026-05-05T08:00:00Z',
  },
  {
    id: 't3',
    title: 'Prepare staff meeting agenda',
    category: 'Staff',
    priority: 'Medium',
    dueDate: '2026-05-08',
    notes: 'Include Q2 vision review and summer series planning.',
    status: 'Todo',
    visibility: 'Organization',
    createdBy: 'u1',
    createdAt: '2026-05-05T10:00:00Z',
    updatedAt: '2026-05-05T10:00:00Z',
  },
  {
    id: 't4',
    title: 'Order communion supplies for May',
    category: 'Sunday Service',
    priority: 'Medium',
    dueDate: '2026-05-10',
    status: 'Todo',
    visibility: 'Organization',
    createdBy: 'u4',
    assignedTo: 'u4',
    createdAt: '2026-05-03T11:00:00Z',
    updatedAt: '2026-05-03T11:00:00Z',
  },
  {
    id: 't5',
    title: 'Update church website with summer series info',
    category: 'Admin',
    priority: 'Low',
    dueDate: '2026-05-15',
    status: 'Waiting',
    visibility: 'Organization',
    createdBy: 'u4',
    createdAt: '2026-05-04T13:00:00Z',
    updatedAt: '2026-05-04T13:00:00Z',
  },
  {
    id: 't6',
    title: 'Plan youth volunteer appreciation night',
    category: 'Staff',
    priority: 'Low',
    dueDate: '2026-05-20',
    status: 'Todo',
    visibility: 'Organization',
    createdBy: 'u2',
    createdAt: '2026-05-02T09:00:00Z',
    updatedAt: '2026-05-02T09:00:00Z',
  },
  {
    id: 't7',
    title: 'Research new worship songs for June',
    category: 'Sunday Service',
    priority: 'Medium',
    dueDate: '2026-05-14',
    notes: 'Need 3–4 new songs that fit the summer series theme.',
    status: 'In Progress',
    visibility: 'Organization',
    createdBy: 'u3',
    assignedTo: 'u3',
    claimedBy: 'u3',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-04T15:00:00Z',
  },
  {
    id: 't8',
    title: 'Complete internship reflection journal',
    category: 'Personal',
    priority: 'Medium',
    dueDate: '2026-05-12',
    status: 'In Progress',
    visibility: 'Private',
    createdBy: 'u5',
    assignedTo: 'u5',
    createdAt: '2026-04-28T08:00:00Z',
    updatedAt: '2026-05-03T09:00:00Z',
  },
];

export const SAMPLE_PEOPLE: Person[] = [
  {
    id: 'p1',
    name: 'James Henderson',
    careCategory: 'Grieving',
    lastContactDate: '2026-05-04',
    nextFollowUpDate: '2026-05-07',
    notes: 'Lost his father on May 2nd. Wife is Margaret. Two adult children — Kyle and Anne. Attending Sunday service but visibly struggling.',
    status: 'Needs Attention',
    visibility: 'Organization',
    createdBy: 'u1',
    createdAt: '2026-05-03T10:00:00Z',
    updatedAt: '2026-05-04T08:00:00Z',
  },
  {
    id: 'p2',
    name: 'Maria Santos',
    careCategory: 'New Visitor',
    lastContactDate: '2026-05-03',
    nextFollowUpDate: '2026-05-10',
    notes: 'Visited for the second time. Moved here from Phoenix. Single mother with two kids. Interested in small group.',
    status: 'In Progress',
    visibility: 'Organization',
    createdBy: 'u2',
    createdAt: '2026-04-27T11:00:00Z',
    updatedAt: '2026-05-03T12:00:00Z',
  },
  {
    id: 'p3',
    name: 'Robert Keller',
    careCategory: 'Hospital Visit',
    lastContactDate: '2026-05-02',
    nextFollowUpDate: '2026-05-06',
    notes: 'Hip replacement surgery on April 30. Recovering at St. Mary\'s Medical. Spirits good. Wife Linda is with him.',
    status: 'In Progress',
    visibility: 'Organization',
    createdBy: 'u1',
    createdAt: '2026-04-30T09:00:00Z',
    updatedAt: '2026-05-02T14:00:00Z',
  },
  {
    id: 'p4',
    name: 'Angela Reeves',
    careCategory: 'Counseling',
    lastContactDate: '2026-04-28',
    nextFollowUpDate: '2026-05-12',
    notes: 'Ongoing pastoral counseling. Marriage difficulties. Meeting bi-weekly. Referral to professional counselor being considered.',
    status: 'In Progress',
    visibility: 'Private',
    createdBy: 'u1',
    createdAt: '2026-03-15T10:00:00Z',
    updatedAt: '2026-04-28T16:00:00Z',
  },
  {
    id: 'p5',
    name: 'Tom Whitfield',
    careCategory: 'Inactive Member',
    lastContactDate: '2026-03-10',
    nextFollowUpDate: '2026-05-15',
    notes: 'Has not attended in about 8 weeks. Previously very involved in men\'s ministry. Worth a personal call.',
    status: 'Needs Attention',
    visibility: 'Organization',
    createdBy: 'u2',
    createdAt: '2026-03-20T09:00:00Z',
    updatedAt: '2026-04-01T10:00:00Z',
  },
  {
    id: 'p6',
    name: 'Diane Okafor',
    careCategory: 'Volunteer Leader',
    lastContactDate: '2026-05-01',
    nextFollowUpDate: '2026-05-20',
    notes: 'Leading children\'s ministry team. Expressed feeling stretched. Good conversation — wants to talk about delegation.',
    status: 'Stable',
    visibility: 'Organization',
    createdBy: 'u1',
    createdAt: '2026-04-10T09:00:00Z',
    updatedAt: '2026-05-01T11:00:00Z',
  },
];

export const SAMPLE_SERMONS: Sermon[] = [
  {
    id: 's1',
    title: 'Rooted: Abiding in the Vine',
    scriptureText: 'John 15:1–11',
    seriesName: 'Rooted — Summer Series 2026',
    preachingDate: '2026-05-11',
    status: 'Drafting',
    bigIdea: 'Fruitfulness flows from proximity to Jesus — not from effort, but from abiding.',
    notes: 'Open with gardening illustration. Three points: (1) The Vine and the Branch, (2) The Pruning Process, (3) The Promise of Fruit. Close with invitation to sit with Jesus this week.',
    createdBy: 'u1',
    createdAt: '2026-04-20T09:00:00Z',
    updatedAt: '2026-05-05T14:00:00Z',
  },
  {
    id: 's2',
    title: 'Rooted: Nourished by the Word',
    scriptureText: 'Psalm 1',
    seriesName: 'Rooted — Summer Series 2026',
    preachingDate: '2026-05-18',
    status: 'Outlining',
    bigIdea: 'The person who meditates on God\'s Word is like a tree planted by water — always fruitful, always sustained.',
    notes: 'Contrast with the way of the wicked. Strong visual opportunity with tree/river imagery.',
    createdBy: 'u1',
    createdAt: '2026-04-25T10:00:00Z',
    updatedAt: '2026-05-03T09:00:00Z',
  },
  {
    id: 's3',
    title: 'When Peace Feels Impossible',
    scriptureText: 'Philippians 4:4–9',
    seriesName: undefined,
    preachingDate: '2026-05-25',
    status: 'Idea',
    bigIdea: 'The peace that surpasses understanding is guarded, not earned — it comes through prayer, gratitude, and a mind anchored in truth.',
    notes: 'Potential Memorial Day connection — peace in the midst of a divided world. May develop this into its own series.',
    createdBy: 'u1',
    createdAt: '2026-05-01T08:00:00Z',
    updatedAt: '2026-05-01T08:00:00Z',
  },
];

export const SAMPLE_PRAYER_REQUESTS: PrayerRequest[] = [
  {
    id: 'pr1',
    personName: 'Robert Keller',
    request: 'Full recovery from hip replacement surgery. Pray for minimal complications and for Linda to have strength as his caregiver.',
    category: 'Health',
    dateAdded: '2026-04-30',
    followUpDate: '2026-05-14',
    status: 'Active',
    visibility: 'Organization',
    createdBy: 'u1',
    createdAt: '2026-04-30T09:00:00Z',
    updatedAt: '2026-04-30T09:00:00Z',
  },
  {
    id: 'pr2',
    personName: 'Henderson Family',
    request: 'Peace and comfort in the loss of their father. Pray for James especially — he is carrying a lot.',
    category: 'Grief',
    dateAdded: '2026-05-03',
    followUpDate: '2026-05-17',
    status: 'Active',
    visibility: 'Organization',
    createdBy: 'u1',
    createdAt: '2026-05-03T08:00:00Z',
    updatedAt: '2026-05-03T08:00:00Z',
  },
  {
    id: 'pr3',
    personName: 'Maria Santos',
    request: 'Wisdom and courage as she settles her family into a new city and finds community here.',
    category: 'Family',
    dateAdded: '2026-04-27',
    followUpDate: '2026-05-11',
    status: 'Active',
    visibility: 'Organization',
    createdBy: 'u2',
    createdAt: '2026-04-27T11:00:00Z',
    updatedAt: '2026-04-27T11:00:00Z',
  },
  {
    id: 'pr4',
    personName: 'Staff Team',
    request: 'Unity, joy, and vision clarity as we head into the summer season. Protect us from burnout.',
    category: 'Church/Ministry',
    dateAdded: '2026-05-01',
    status: 'Active',
    visibility: 'Organization',
    createdBy: 'u1',
    createdAt: '2026-05-01T09:00:00Z',
    updatedAt: '2026-05-01T09:00:00Z',
  },
  {
    id: 'pr5',
    personName: 'Building Fund',
    request: 'Provision for the new children\'s wing expansion. We need $240K more by year-end.',
    category: 'Church/Ministry',
    dateAdded: '2026-03-01',
    followUpDate: '2026-06-01',
    status: 'Active',
    privateNotes: 'Two major donors have indicated interest. Follow up with the Petersons in June.',
    visibility: 'Organization',
    createdBy: 'u1',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-04-15T09:00:00Z',
  },
];

export const SAMPLE_RHYTHM_ITEMS: RhythmItem[] = [
  { id: 'r1', title: 'Sermon Prep', description: 'Dedicated time in the Word preparing for Sunday', isRecurring: true, completedDates: [] },
  { id: 'r2', title: 'Staff Meeting', description: 'Weekly team alignment and prayer', isRecurring: true, completedDates: [] },
  { id: 'r3', title: 'Member Follow-Up', description: 'Calls, visits, and pastoral care connections', isRecurring: true, completedDates: [] },
  { id: 'r4', title: 'Personal Prayer Time', description: 'Unhurried time with God before the work begins', isRecurring: true, completedDates: [] },
  { id: 'r5', title: 'Hospital / Home Visits', description: 'Physical presence with those who are suffering', isRecurring: true, completedDates: [] },
  { id: 'r6', title: 'Sunday Service Review', description: 'What went well? What needs attention?', isRecurring: true, completedDates: [] },
  { id: 'r7', title: 'Sabbath / Rest', description: 'Full rest — no ministry work', isRecurring: true, completedDates: [] },
  { id: 'r8', title: 'Family Time', description: 'Protected, present time with family', isRecurring: true, completedDates: [] },
  { id: 'r9', title: 'Leadership Development', description: 'Reading, podcasts, or mentorship for growth', isRecurring: true, completedDates: [] },
];
